[package]
name = "defmt-serial"
version = "0.1.0"
edition = "2021"
authors = [ "Gaute Hope <eg@gaute.vetsj.com>" ]
description = "Log defmt-messages over serial"
license = "MIT"
repository = "https://github.com/gauteh/defmt-serial"


[dependencies]
critical-section = "0.2.7"
defmt = "0.3.2"
embedded-hal = "1.0.0-alpha.8"
nb = "1.0.0"
