[package]
name = "defmt-serial"
version = "0.1.0"
edition = "2021"
authors = [ "Gaute Hope <eg@gaute.vetsj.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "0.3.2"
embedded-hal = "0.2.7"
