[package]
name = "example-std"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io = "0.6"
defmt = "0.3.2"
defmt-serial = { version = "*", path = "../" }
nb = "1.0.0"
critical-section = { version = "1.1", features = ["std"]}
static_cell = "2.0.0"
