name: Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Add rust target for thumbv7em
        run: |
          rustup target add thumbv7em-none-eabihf

      - name: Build
        run: cargo build --verbose

      - name: Build artemis example
        working-directory: example-artemis
        run: cargo build --verbose

      - name: Build pi-pico example
        working-directory: example-pi-pico
        run: cargo build --verbose

      - name: Build std example
        working-directory: example-std
        run: cargo build --verbose

      - name: Run std example
        working-directory: example-std
        run: cargo run --verbose


